# Generated by Django 6.0 on 2025-12-11 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cedula')),
                ('procedencia', models.CharField(max_length=150, verbose_name='Lugar de procedencia')),
                ('motivo_visita', models.TextField(verbose_name='Motivo de la visita')),
                ('fecha_hora_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Entrada')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_hora_entrada'],
            },
        ),
    ]
