# Generated by Django 6.0 on 2025-12-12 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['-fecha_hora_ingreso'], 'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='fecha_hora_entrada',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='procedencia',
        ),
        migrations.AddField(
            model_name='visitante',
            name='atencion_completada',
            field=models.BooleanField(default=False, verbose_name='Atención completada'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='lugar_procedencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Lugar de procedencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='tipo_visita',
            field=models.CharField(choices=[('REUNION', 'Reunión'), ('ENTREVISTA', 'Entrevista'), ('ENTREGA', 'Entrega de documentos'), ('RECOGIDA', 'Recogida de materiales'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTRO', 'Otro')], default='REUNION', max_length=20, verbose_name='Tipo de visita'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
