# Generated by Django 6.0 on 2025-12-11 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_visitante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='telefono',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='tipo_visita',
            field=models.CharField(choices=[('ASESORIA', 'Asesoria'), ('DIVORCIO_MUTUO_ACUERDO', 'Divorcio Mutuo Acuerdo'), ('DIVORCIO_POR_DESAFECTO', 'Divorcio por Desafecto'), ('CURATELA', 'Curatela'), ('TUTELA', 'TUTELA'), ('DECLARACION_DE_UNICOS_HEREDERERO', 'Declaracion de Unicos Herederos Universales'), ('MEDIDA_ANTICIPADA_PROHIBICION_SALIDA_PAIS', 'Medida Anticipada Prohibicion Salida del Pais'), ('PERMISO_PARA_ESTUDIOS_MENORES', 'Permiso para Estudios Menores de edad en Instituciones de seguridad'), ('REGIMEN_MANUTENCION', 'Regimen de Manutencion'), ('REGIMEN_CONVICENCIA', 'Regimen de Convivencia'), ('CARTA_SOLTERIA', 'Carta de Solteria'), ('IMPUGNACION_DE_PATERNIDAD', 'Impugnacion de Paternidad'), ('PERMISOS_DE_VIAJE', 'Permisos de Viajes'), ('TITULO_SUPLITORIO', 'Titulo Suplitorios'), ('OTRO', 'Otro')], default='ASESORIA', max_length=80, verbose_name='Tramites '),
        ),
    ]
