# Generated by Django 6.0 on 2025-12-28 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_visitante_telefono_alter_visitante_tipo_visita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='lugar_procedencia',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='motivo_visita',
        ),
        migrations.AddField(
            model_name='visitante',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección completa'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='historial',
            field=models.TextField(blank=True, null=True, verbose_name='Historial de cambios'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='otra_institucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especifique otra institución'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parroquia'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='referir_a',
            field=models.CharField(choices=[('MINISTERIO_PUBLICO', 'Ministerio Público'), ('DEFENSORIA_DEL_PUEBLO', 'Defensoría del Pueblo'), ('PREFECTURA', 'Prefectura'), ('JUECES_DE_PAZ', 'Jueces de Paz'), ('REGISTRO_INMOBILIARIO', 'Registro Inmobiliario'), ('REGISTRO_MERCANTIL', 'Registro Mercantil'), ('REGISTRO_PRINCIPAL', 'Registro Principal'), ('REGISTRO_CIVIL', 'Registro Civil'), ('NOTARIA_PUBLICA', 'Notaría Pública'), ('COMANDANCIA_POLICIA', 'Comandancia de la Policía'), ('CICPC', 'CICPC'), ('POLICIA_NACIONAL_BOLIVARIANA', 'Policía Nacional Bolivariana'), ('GOBERNACION', 'Gobernación'), ('ALCALDIA', 'Alcaldía'), ('DEFENSA_PUBLICA', 'Defensa Pública'), ('SENIAT', 'SENIAT'), ('SEMAT', 'SEMAT'), ('SUNDEE', 'SUNDEE'), ('SEMAMECF', 'SEMAMECF'), ('INAMUJER', 'INAMUJER'), ('URDD', 'URDD'), ('OAP', 'OAP'), ('TRIBUNAL_SUPREMO_JUSTICIA', 'Tribunal Supremo de Justicia (esta misma institución)'), ('OTRA_INSTITUCION', 'Otra Institución'), ('NO_REFERIDO', 'No requiere referir')], default='NO_REFERIDO', max_length=50, verbose_name='Referir a institución para resolver el caso'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='tipo_visita',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('DIVORCIO_MUTUO_ACUERDO', 'Divorcio Mutuo Acuerdo'), ('DIVORCIO_POR_DESAFECTO', 'Divorcio por Desafecto'), ('CURATELA', 'Curatela'), ('TUTELA', 'Tutela'), ('DECLARACION_DE_UNICOS_HEREDERERO', 'Declaración de Únicos Herederos Universales'), ('MEDIDA_ANTICIPADA_PROHIBICION_SALIDA_PAIS', 'Medida Anticipada Prohibición Salida del País'), ('PERMISO_PARA_ESTUDIOS_MENORES', 'Permiso para Estudios Menores de edad en Instituciones de seguridad'), ('REGIMEN_MANUTENCION', 'Régimen de Manutención'), ('REGIMEN_CONVIVENCIA', 'Régimen de Convivencia'), ('CARTA_SOLTERIA', 'Carta de Soltería'), ('IMPUGNACION_DE_PATERNIDAD', 'Impugnación de Paternidad'), ('PERMISOS_DE_VIAJE', 'Permisos de Viajes'), ('TITULO_SUPLITORIO', 'Título Supletorio'), ('OTRO', 'Otro')], default='ASESORIA', max_length=80, verbose_name='Tipo de trámite solicitado'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['cedula'], name='gestion_vis_cedula_ce6fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['tipo_visita'], name='gestion_vis_tipo_vi_ae005d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['referir_a'], name='gestion_vis_referir_d824f3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['atencion_completada'], name='gestion_vis_atencio_8907d9_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['fecha_hora_ingreso'], name='gestion_vis_fecha_h_144e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['municipio'], name='gestion_vis_municip_914528_idx'),
        ),
    ]
