# Generated by Django 6.0 on 2025-12-29 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_visitante_lugar_procedencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'indexes': [models.Index(fields=['cedula'], name='gestion_per_cedula_67826c_idx')],
            },
        ),
        migrations.AddField(
            model_name='visitante',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='gestion.persona'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['persona'], name='gestion_vis_persona_01c983_idx'),
        ),
    ]
