# Generated by Django 6.0 on 2026-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_visitante_cedula_persona_visitante_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='referir_a',
            field=models.CharField(choices=[('PROTECCION', 'Protección'), ('CIVIL', 'Civil'), ('LABORAL', 'Laboral'), ('PENAL', 'Penal'), ('VIOLENCIA_DE_GENERO', 'Violencia de Género'), ('MINISTERIO_PUBLICO', 'Ministerio Público'), ('DEFENSORIA_DEL_PUEBLO', 'Defensoría del Pueblo'), ('PREFECTURA', 'Prefectura'), ('JUECES_DE_PAZ', 'Jueces de Paz'), ('REGISTRO_INMOBILIARIO', 'Registro Inmobiliario'), ('REGISTRO_MERCANTIL', 'Registro Mercantil'), ('REGISTRO_PRINCIPAL', 'Registro Principal'), ('REGISTRO_CIVIL', 'Registro Civil'), ('NOTARIA_PUBLICA', 'Notaría Pública'), ('COMANDANCIA_POLICIA', 'Comandancia de la Policía'), ('CICPC', 'CICPC'), ('POLICIA_NACIONAL_BOLIVARIANA', 'Policía Nacional Bolivariana'), ('GOBERNACION', 'Gobernación'), ('ALCALDIA', 'Alcaldía'), ('DEFENSA_PUBLICA', 'Defensa Pública'), ('SENIAT', 'SENIAT'), ('SEMAT', 'SEMAT'), ('SUNDEE', 'SUNDEE'), ('SEMAMECF', 'SEMAMECF'), ('INAMUJER', 'INAMUJER'), ('URDD', 'URDD'), ('OAP', 'OAP'), ('TRIBUNAL_SUPREMO_JUSTICIA', 'Tribunal Supremo de Justicia (esta misma institución)'), ('OTRA_INSTITUCION', 'Otra Institución'), ('NO_REFERIDO', 'No requiere referir')], default='NO_REFERIDO', max_length=50, verbose_name='Referir a institución para resolver el caso'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='tipo_visita',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('DIVORCIO_MUTUO_ACUERDO', 'Divorcio Mutuo Acuerdo'), ('DIVORCIO_POR_DESAFECTO', 'Divorcio por Desafecto'), ('CURATELA', 'Curatela'), ('TUTELA', 'Tutela'), ('DECLARACION_DE_UNICOS_HEREDERERO', 'Declaración de Únicos Herederos Universales'), ('MEDIDA_ANTICIPADA_PROHIBICION_SALIDA_PAIS', 'Medida Anticipada Prohibición Salida del País'), ('PERMISO_PARA_ESTUDIOS_MENORES', 'Permiso para Estudios Menores de edad en Instituciones de seguridad'), ('REGIMEN_MANUTENCION', 'Régimen de Manutención'), ('REGIMEN_CONVIVENCIA', 'Régimen de Convivencia'), ('CARTA_SOLTERIA', 'Carta de Soltería'), ('IMPUGNACION_DE_PATERNIDAD', 'Impugnación de Paternidad'), ('PERMISOS_DE_VIAJE', 'Permisos de Viajes'), ('TITULO_SUPLITORIO', 'Título Supletorio'), ('EJERCICIO_UNILATERAL_PATRIA_POTESTAD', 'Ejercicio Unilateral de la Patria Potestad'), ('COLOCACION_FAMILIAR', 'Colocación Familiar'), ('CAMBIO_DE_RESIDENCIA_INTERNACIONAL', 'Cambio de Residencia Internacional'), ('UNION_ESTABLE_POST_MORTEN', 'Unión Estable Post Mortem'), ('CUSTODIA', 'Custodia'), ('OTRO', 'Otro')], default='ASESORIA', max_length=80, verbose_name='Tipo de trámite solicitado'),
        ),
    ]
