# Generated by Django 6.0 on 2026-03-09 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_visitante_referir_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión')], max_length=10, verbose_name='Acción')),
                ('modulo', models.CharField(blank=True, max_length=100, verbose_name='Módulo / Modelo')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del registro afectado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario'], name='gestion_aud_usuario_c96997_idx'), models.Index(fields=['accion'], name='gestion_aud_accion_6e0fb1_idx'), models.Index(fields=['fecha'], name='gestion_aud_fecha_1ccfcb_idx'), models.Index(fields=['modulo'], name='gestion_aud_modulo_0b3011_idx')],
            },
        ),
    ]
